### ISSUE TITLE
correções

### ISSUE THREAD

**Issue by luise-flores** [brunobandev/translated-code#3]
1. Ninguém é perfeito - os erros acontecem com muito mais frequência do que deveriam, e isso é realmente bom desde que aprendemos com esses erros. -> aprendamos

2. Quando você lida com um código que não pode ser testado, uma vez que é mal projetado e o código é abaixo do ideal, você tem alguns problemas maiores. ->  está mal projetado e o código está abaixo do ideal

A falta de testes os deixa ansiosos, pois não têm a confirmação de que suas alterações não quebraram nada. ->  quebrarão

3. não a torne opcional. -> não os torne (os testes) opcional.

5. Você também deseja dar uma olhada nas versões atuais ou mais antigas do aplicativo - se possível, é claro. ->  deseja ou deve?

6. As pessoas mudam de idéia por muitas razões e o fazem regularmente. ->  as fazem 

Para finaLizar -> Acho que todos nós já usamos um desses antes. uma dessas (desculpas)

**Comment by brunobandev** [comment]
Thank  you @luise-flores.
